### ISSUE TITLE
Not working anymore with new Zyxel firmwares

### ISSUE THREAD

**Issue by cryptage21** [cretl/gs1200hp-ctrl#2]
Hi,

In new firmwares (GS1200-5/5HPv2/8/8HPv2), Zyxel added an encryption algorithm for password authentication.
It seems it's not working anymore.

Are you able to solve this problem ? 

Regards

**Comment by cretl** [comment]
Hi,
I can confirm the problem.
In the newest firmware the password is "encrypted" by a simple JS-function. When using the "encrypted" version of the password instead of the clear text one, the script still works.

As a workaround you can "encrypt" your password with this simple function by logging into the web interface of the switch. The Firefox network analysis tool (developer tools menu) shows your “encrypted” password.

I’ll try to adapt the script.

Kind regards

**Comment by cretl** [comment]
I adapted the script (v0.12). It works (at least for me) properly.
